### ISSUE TITLE
Registration Issue

### ISSUE THREAD

**Issue by 1724229** [1724412/CO5027_Test#2]
Registration successful even when validator is triggered.
 https://imgur.com/WW2Me96
![image](https://user-images.githubusercontent.com/47967415/57059480-2d50e700-6ce8-11e9-8cae-1f3a9a8b7c68.png)

**Comment by 1724412** [comment]
Resolved

**Comment by 1724412** [comment]
Resolved

**Comment by 1724412** [comment]
Resolved
